# Generated by Django 5.2.8 on 2025-12-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
